workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - ios-signing
    integrations:
      app_store_connect: 8897f779-7d3e-4d54-83f1-b9559f56f8bf862753c4-6d71-4f23-afe5-d7a0dd4238a7
    scripts:
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: | 
          app-store-connect fetch-signing-files "$(xcode-project detect-bundle-id)" \
            --type IOS_APP_DEVELOPMENT \
            --create
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles