// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_config/flutter_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: FlutterConfig.get('ANDROID_API_KEY') ?? "",
    authDomain: "infinite-sports-app.firebaseapp.com",
    appId: '1:248087010229:android:058f3dbffbc0a468',
    messagingSenderId: '248087010229',
    projectId: 'infinite-sports-app',
    databaseURL: 'https://infinite-sports-app.firebaseio.com',
    storageBucket: 'infinite-sports-app.appspot.com',
    androidClientId: "248087010229-0ko6d3n8v74aok3avl6h54chpc1qbrhe.apps.googleusercontent.com",
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: FlutterConfig.get('IOS_API_KEY') ?? "",
    authDomain: "infinite-sports-app.firebaseapp.com",
    appId: '1:248087010229:ios:87700ab7b56d8baa',
    messagingSenderId: '248087010229',
    projectId: 'infinite-sports-app',
    databaseURL: 'https://infinite-sports-app.firebaseio.com',
    storageBucket: 'infinite-sports-app.appspot.com',
    iosClientId:
        '248087010229-g45omq0n7ev5jtmbc1ei7a0nuaq02544.apps.googleusercontent.com',
    iosBundleId: 'com.infinitesports.Infinite-Sports',
  );
}
